source 'https://github.com/Artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :'ios', '8.0'
project 'FacebookImagePicker.xcodeproj'

target 'FacebookImagePicker' do
	pod 'FBSDKCoreKit', '~> 4.20.2'
	pod 'FBSDKLoginKit', '~> 4.20.2'
end
